### ISSUE TITLE
`npx sequelize-cli db:migrate` error with new build

### ISSUE THREAD

**Issue by rjpadilla** [earthowned/planetfarms#430]
* Cloned a new repo to start over with planetfarms
* Changed the .env to work with cognito
* When running `npx sequelize-cli db:migrate` I recieved this error: 
```
== 20210720165840-alter-table-enrolls-add-column-remove_enroll_courseId_unique_key: migrating =======
(node:14715) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: column "courseId" of relation "enrolls" already exists
    at Query.formatError (/mnt/c/Users/RJ/Desktop/earthowned/planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/mnt/c/Users/RJ/Desktop/earthowned/planetfarms/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /mnt/c/Users/RJ/Desktop/earthowned/planetfarms/api/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.addColumn (/mnt/c/Users/RJ/Desktop/earthowned/planetfarms/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:408:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14715) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
== 20210720165840-alter-table-enrolls-add-column-remove_enroll_courseId_unique_key: migrated (0.112s) 
```
Running it: 
![image](https://user-images.githubusercontent.com/23529006/128568203-d415d211-8eae-41ff-ab89-8871e0e3901c.png)

Confirming with Github Actions: https://github.com/earthowned/planetfarms/runs/3265706110?check_suite_focus=true#step:4:143

**Comment by rjpadilla** [comment]
Error persists with localhost as well.

**Comment by rjpadilla** [comment]
Nevermind, had another database open.

**Comment by rjpadilla** [comment]
@dogi doesn't think its the database for the error I'm getting.

**Comment by rjpadilla** [comment]
@lmmrssa says that there are migrations with missing `awaits` that can cause conflicting queries. 
See: https://github.com/earthowned/planetfarms/blob/742eae385d18c31590a5cbf65b8f013796a0ce99/api/src/migrations/20210720165840-alter-table-enrolls-add-column-remove_enroll_courseId_unique_key.js#L2-L17

**Comment by lmmrssa** [comment]
@rjpadilla while fixing also make sure down query is doing remove before add as it will also have conflict else
